<?php

/**
 * @file
 * Contains thunder_print hook implementation.
 */

use Drupal\Core\Url;
use Drupal\views\Views;
use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_operation().
 */
function thunder_print_entity_operation(EntityInterface $entity) {

  $operations = array();

  /** @var \Drupal\workspace\Entity\WorkspaceInterface $active_workspace */
  $active_workspace = \Drupal::service('workspace.manager')
    ->getActiveWorkspace(TRUE);

  if ($entity->getEntityTypeId() == 'node' && $entity->bundle() == 'article' && $active_workspace->id() == 'live') {
    $operations['migrate_to_print'] = array(
      'title' => t('Migrate to print'),
      'url' => Url::fromRoute('thunder_print.migrate', ['node' => $entity->id()]),
      'weight' => 50,
    );
  }

  return $operations;
}

/**
 * Implements hook_views_query_alter().
 */
function thunder_print_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

  /** @var \Drupal\workspace\WorkspaceManagerInterface $workspace_manager */
  $workspace_manager = \Drupal::service('workspace.manager');
  $active_workspace = $workspace_manager->getActiveWorkspace();

  $entity_type = $view->getBaseEntityType();
  if (!$workspace_manager->entityTypeCanBelongToWorkspaces($entity_type)) {
    return;
  }

  $configuration = [
    'table' => 'content_workspace_field_revision',
    'field' => 'content_entity_revision_id',
    'left_table' => $entity_type->getDataTable(),
    'left_field' => $entity_type->getKey('revision'),
    'operator' => '=',
  ];
  /** @var \Drupal\views\Plugin\views\join\JoinPluginBase $join */
  $join = Views::pluginManager('join')->createInstance('standard', $configuration);
  /** @var \Drupal\views\Plugin\views\query\Sql $query */
  $query->addRelationship('cwrf', $join, 'content_workspace_field_revision');

  if ($active_workspace == 'print') {
    $query->addWhere(0, 'cwrf.workspace', [$active_workspace], 'IN');
  }
  else {
    $query->addWhere(0, 'cwrf.workspace', ['print'], 'NOT IN');
  }

}
